@RestApiTemplate_HostAddress = http://localhost:5173

### Register a new user
POST {{RestApiTemplate_HostAddress}}/auth/register
Content-Type: application/json
{
  "name": "",
  "email": "",
  "password": ""
}

### Login to get JWT token
POST {{RestApiTemplate_HostAddress}}/auth/login
Content-Type: application/json
{
  "email": "",
  "password": ""
}

### 
GET {{RestApiTemplate_HostAddress}}/weatherforecast/
Content-Type: application/json

###
GET {{RestApiTemplate_HostAddress}}/User
Authorization: Bearer 

###
GET {{RestApiTemplate_HostAddress}}/User/2
Authorization: Bearer
